### ISSUE TITLE
Go tip compilation error

### ISSUE THREAD

**Issue by chrislusf** [zentures/encoding#4]
# github.com/dataence/encoding
asm: invalid instruction: 00006 (/home/travis/gopath/src/github.com/dataence/encoding/bitlen_amd64.s:6)	JEQ	Z1
asm: assembly failed

**Comment by rexshang** [comment]
@chrislusf How did you solve this issue?  I am starting to see this problem.

**Comment by chrislusf** [comment]
stopped using this package.

**Comment by MoZhonghua** [comment]
just change label "Z1" to lower case. 

maybe golang has changed the label naming requirement.
